/**
 * Auto-post from Receipt.
 *
 * When `submit_attempt` mints a Receipt, we drop a short feed post in
 * the builder's name. Cuts post effort to zero — every Receipt becomes
 * organic content without builder labor.
 *
 * The drafted headline is intentionally short and factual. Real product
 * UX would let the builder edit before publish; v0 publishes
 * immediately and lets them delete (or edit later).
 *
 * Headline is generated by Claude Sonnet 4.6 if ANTHROPIC_API_KEY is
 * set; otherwise we use a deterministic template. Either way the post
 * lands within the same submit_attempt response cycle.
 */

import Anthropic from "@anthropic-ai/sdk";
import { createPost } from "@/lib/posts/store";
import type { Brief, Fingerprint } from "@/lib/receipts/types";

export async function autoPostFromReceipt(input: {
  builderId: string;
  builderUsername: string;
  builderName: string;
  builderGradient: string;
  brief: Brief;
  composite: number;
  fingerprint: Fingerprint;
  receiptId: string;
}): Promise<void> {
  const isWin = input.composite >= 80;

  const headline = await draftHeadline({
    brief: input.brief,
    composite: input.composite,
    fingerprint: input.fingerprint,
    isWin,
  });

  try {
    await createPost({
      authorId: input.builderId,
      authorUsername: input.builderUsername,
      authorName: input.builderName,
      authorGradient: input.builderGradient,
      kind: isWin ? "hack-win" : "receipt",
      verb: isWin
        ? "topped the leaderboard on"
        : "minted a Receipt on",
      headline,
      subtext: input.brief.tagline,
      href: `/receipts/${input.receiptId}`,
      badges: [input.brief.difficulty, input.brief.category],
      metric: { label: "Score", value: String(input.composite) },
      receiptId: input.receiptId,
      briefId: input.brief.id,
    });
  } catch (e) {
    // Auto-post is best-effort. Never let it break the submit_attempt flow.
    console.error("[auto-post] failed:", e);
  }
}

async function draftHeadline(input: {
  brief: Brief;
  composite: number;
  fingerprint: Fingerprint;
  isWin: boolean;
}): Promise<string> {
  // No Anthropic key → deterministic template.
  if (!process.env.ANTHROPIC_API_KEY) {
    return templateHeadline(input);
  }

  try {
    const client = new Anthropic();
    const topDim = (Object.entries(input.fingerprint) as [string, number][])
      .sort((a, b) => b[1] - a[1])[0];

    const response = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 200,
      system: `You write one-line social-feed headlines for builders who just minted a Receipt on Antry.

Rules:
  - 60–120 characters total.
  - First person, factual, no hype.
  - Mention what they shipped or the standout Fingerprint dimension.
  - No emoji unless the score is 95+ (then one fire/lightning at most).
  - No "I just" — drop the "just."
  - No marketing words ("amazing", "stoked", "thrilled").

Output: just the headline string. No quotes, no preamble.`,
      messages: [
        {
          role: "user",
          content: `Brief: ${input.brief.title}
Tagline: ${input.brief.tagline}
Score: ${input.composite}/100 ${input.isWin ? "(top of leaderboard)" : ""}
Top Fingerprint dimension: ${topDim[0]} at ${topDim[1]}

Write the headline.`,
        },
      ],
    });
    const txt = response.content.find(
      (b): b is Anthropic.TextBlock => b.type === "text"
    );
    if (!txt) return templateHeadline(input);
    const headline = txt.text.trim().replace(/^["']|["']$/g, "");
    if (headline.length < 20 || headline.length > 200) {
      return templateHeadline(input);
    }
    return headline;
  } catch (e) {
    console.error("[auto-post] draft failed:", e);
    return templateHeadline(input);
  }
}

function templateHeadline(input: {
  brief: Brief;
  composite: number;
  isWin: boolean;
}): string {
  if (input.isWin) {
    return `Topped the ${input.brief.title} leaderboard at ${input.composite}/100.`;
  }
  return `Shipped ${input.brief.title} — composite ${input.composite}/100.`;
}
